# Exceções, contextos e NumPy

## NumPy

A biblioteca Numpy é a mais importante biblioteca para quem usa Python para aplicações científicas.

Ela é parte de um conjunto de ferramentas Python voltadas para ciência denominado [SciPy](https://scipy.org/), que inclui NumPy (arrays e matrizes), SciPy propriamente dito (cálculos numéricos), IPython (para interface com Python), Matplotlib (para gráficos), SymPy (matemática simbólica) e Pandas (análise de dados), entre outras.

Numpy é uma biblioteca que permite definir *arrays* e matrizes e lidar com os mesmos de forma simples e eficiente.

*Arrays* são estruturas de dados onde todos os elementos são idênticos e estão armazenados em posições consecutivas de memória. Isso faz com que eles sejam menos versáteis do que a principal estrutura de dados do Python, a lista, mas por outro lado, faz com que o processamento seja muito mais eficiente. A eficiência é ainda maior pelo fato de NumPy fornecer diversas operações em *arrays* que são implementadas diretamente em C, e portanto não incorrem nos custos de interpretação de Python.

Para usar NumPy, devemos importar o módulo `numpy`, o que é convencionalmente feito da seguinte forma:

In [10]:
import numpy as np

Como `numpy` define uma grande quantidade de funções, seria inconveniente usar

    from numpy import *
    
O método usado acima permite economizar nas chamadas das funções de `numpy` usando apenas `np`. Como é uma convenção amplamente seguida, é também fácil de identificar no código.

Para criar um *array*, podemos converter uma lista Python para um *array*:

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

No caso de *arrays*, os implementadores optaram por mostrar o *array* no interpretador de forma distinta do que é mostrado quando se converte para cadeia de caracteres. Isto é, as implementações de `__repr__` e `__str__` são diferentes:

In [12]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [13]:
a

array([1, 2, 3, 4, 5])

Os elementos do *array* têm todos o mesmo tipo. Se não for especificado um tipo, o NumPy tenta usar o tipo mais apropriado, de acordo com os valores na lista original.

In [14]:
b = np.array([1., 2., 3.])

In [15]:
b

array([ 1.,  2.,  3.])

Para saber o tipo dos elementos de um *array*, podemos acessar seu atributo `dtype`.

In [16]:
b.dtype

dtype('float64')

In [17]:
a.dtype

dtype('int32')

Se a lista tem tipos mistos, o NumPy tenta usar o tipo mais abrangente.

In [18]:
c = np.array([1, 2., 3])

In [19]:
c.dtype

dtype('float64')

In [20]:
c

array([ 1.,  2.,  3.])

In [21]:
np.array([1, 2, 'funciona isto?'])

array(['1', '2', 'funciona isto?'], 
      dtype='<U14')

Note como no caso acima ele converteu os números para cadeias de caracteres.

Podemos também criar *arrays* de duas dimensões, passando listas de listas, isto é, uma lista onde cada elemento é uma lista com os valores de uma linha do *array*.

In [22]:
m1 = np.array([[1,2], [3,4], [5,6]])

In [23]:
m1

array([[1, 2],
       [3, 4],
       [5, 6]])

Isso generaliza para um número maior de dimensões.

In [24]:
m2 = np.array([ [ [1,2], [3,4] ], [ [5,6], [7,8] ] ])

In [25]:
m2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

As informações sobre as dimensões de um *array* estão no atributo `shape`, que é uma tupla com o número de elementos em cada dimensão.

In [26]:
a.shape

(5,)

In [27]:
m1.shape

(3, 2)

In [28]:
m2.shape

(2, 2, 2)

Criar *arrays* fornecendo uma lista é uma forma que é conveniente apenas em algumas situações. Normalmente, queremos criar *arrays* grandes diretamente, sem ter que inicialmente criar uma lista (ineficiente).

Existem diversas funções que criam *arrays*. Uma delas é uma generalização de `range`, denominada `arange`. Os valores de início, final e passo podem ser de ponto flutuante.

In [29]:
np.arange(0, 10, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

Outra função similar é a `linspace`, que recebe valor inicial, final e número de valores e gera um *array* onde o primeiro valor é o inicial, o último valor é o final, o total de valores é o número solicitado e os valores são igualmente espaçados.

In [30]:
np.linspace(0, 4, 5)

array([ 0.,  1.,  2.,  3.,  4.])

In [31]:
np.linspace(1, 10, 10)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [32]:
np.linspace(0, 10, 9)

array([  0.  ,   1.25,   2.5 ,   3.75,   5.  ,   6.25,   7.5 ,   8.75,  10.  ])

In [33]:
np.linspace(5,8,8)

array([ 5.        ,  5.42857143,  5.85714286,  6.28571429,  6.71428571,
        7.14285714,  7.57142857,  8.        ])

Vejamos agora um exemplo da vantagem em termos de desempenho no uso de NumPy.

Abaixo temos três funções que fazem a soma de dois conjuntos de valores (listas ou arrays).

A primeira usa listas e faz as contas com um `for`. A segunda usa listas e faz as contas com *list comprehension*. A terceira usa *arrays* e operações de NumPy.

In [34]:
def listasimples(n):
    a = list(range(n))
    b = list(range(1, n+1))
    c = []
    for x, y in zip(a, b):
        c.append(x + y)
    return c

In [35]:
listasimples(10)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [36]:
def listacomp(n):
    a = [i for i in range(n)]
    b = [i for i in range(1, n+1)]
    return [x + y for x, y in zip(a, b)]

In [37]:
listacomp(10)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [38]:
def somanp(n):
    a = np.arange(n)
    b = np.arange(1, n+1)
    return a + b

In [39]:
somanp(10)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Vejamos agora o tempo que essas diversas funções tomam para 1000 valores (os tempos abaixo são do meu computador, execute no seu e teste outros tamanhos).

In [40]:
%timeit listasimples(1000)

10000 loops, best of 3: 158 µs per loop


In [41]:
%timeit listacomp(1000)

10000 loops, best of 3: 150 µs per loop


In [42]:
%timeit somanp(1000)

The slowest run took 18.26 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.07 µs per loop


Já vimos que o atributo `shape` informa sobre as dimensões do *array*.

Além desse atributo, temos também `size` que diz o número total de elementos no *array* e *ndim*, que diz o número de dimensões.

In [43]:
m1.shape

(3, 2)

In [44]:
m1.size

6

In [45]:
m2.shape

(2, 2, 2)

In [46]:
m2.size

8

In [47]:
m1.ndim

2

In [48]:
a.ndim

1

In [49]:
m2.ndim

3

Diversas funções que criam *arrays* têm um parâmetro opcional `dtype` que permite especificar qual o tipo dos elementos do *array* (ao invés de deixar por conta do NumPy deduzir o tipo mais apropriado). Os tipos têm nomes da forma `np.int32`, `np.int64`, `np.float32`, `np.float64`, etc).

In [50]:
m3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype=np.float64)

In [51]:
m3

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

Os elementos que estão no *array* podem ser acessados por indexação, como em listas.

In [52]:
a[3]

4

No caso de *arrays* multidimensionais, usamos vírgulas para separar os índices de cada dimensão.

In [53]:
m3[0,0]

1.0

In [54]:
m3[0,1]

2.0

In [55]:
m3[1,2]

6.0

A indexação também aceita *slices* da forma `ini:fim:passo`, para qualquer dimensão. O resultado é um *array* de dimensão apropriada.

In [56]:
m3[0:2,0]

array([ 1.,  4.])

In [57]:
m3[0:2,0:2]

array([[ 1.,  2.],
       [ 4.,  5.]])

In [58]:
m3[:,2]

array([  3.,   6.,   9.,  12.])

In [59]:
m3[2,:]

array([ 7.,  8.,  9.])

Para arrays de múltiplas dimensões, se fornecemos apenas um índice estamos acessando um sub-array com todas as outras dimensões. Por exemplo, numa matriz, `m[2]` indica a terceira linha:

In [60]:
m3[2]

array([ 7.,  8.,  9.])

Podemos também fixar apenas a última das dimensões, usando a sintaxe `...`:

In [61]:
m3[...,2]

array([  3.,   6.,   9.,  12.])

O método `flatten` retorna um novo *array* com todos os elementos do *array* original, mas de apenas uma dimensão. Se nenhum parâmetro for passado para o método, os elementos são retornados na ordem tradicional de C, quer dizer, primeiro os elementos da primeira linha, depois os da segunda, etc.

In [62]:
m3

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [63]:
m3.flatten()

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.])

Também podemos pedir a ordem tradicional de Fortran passando o parâmetro `'F'`. Essa ordem organiza os valores por colunas:

In [64]:
m3.flatten('F')

array([  1.,   4.,   7.,  10.,   2.,   5.,   8.,  11.,   3.,   6.,   9.,
        12.])

É importante notar que este método retorna um novo *array* com uma cópia dos valores do *array* original.

In [65]:
f1 = m3.flatten()

In [66]:
f1[3]

4.0

In [67]:
f1[3] = -4

In [68]:
f1

array([  1.,   2.,   3.,  -4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.])

In [69]:
m3

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

Como vimos, mexar em `f1` não altera o *array* original `m3`, o que facilita entender o código. Por outro lado, se o *array* for grande, a cópia será custosa tanto em tempo de execução quanto em memória ocupada.

Porisso, NumPy oferece o método `ravel`, que é similar ao `flatten`, mas retorna apenas um novo **view** para o *array* original. Quer dizer, estaremos acessando os mesmos elementos do array original, mas como se eles estivessem organizados de outra forma (unidimensionalmente).

In [70]:
f2 = m3.ravel()

In [71]:
f2

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.])

Se alteramos um elemento de `f2` estamos também alterando o correspondente elemento de `m3`. Não se esqueça disso, para evitar erros em seu código.

In [72]:
f2[3] = -4

In [73]:
f2

array([  1.,   2.,   3.,  -4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.])

In [74]:
m3

array([[  1.,   2.,   3.],
       [ -4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

Além de enxergar um *array* como unidimensional, podemos enxergá-lo em qualquer outro formato que desejarmos (que seja compatível com o original). Basta usarmos o método `reshape` (que também retorna um novo **view** para os dados).

In [75]:
m3.shape

(4, 3)

Como vemos, `m3` é um *array* de 4 linhas por 3 colunas. Podemos também olhá-lo como tendo 3 linhas por 4 colunas.

In [76]:
m4 = m3.reshape((3,4))

In [77]:
m3.shape

(4, 3)

In [78]:
m4.shape

(3, 4)

In [79]:
m4

array([[  1.,   2.,   3.,  -4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])

Como `m4` é só um novo *view* nos dados de `m3`, se alteramos `m4` também alteramos `m3`:

In [80]:
m4[0,0] = 10

In [81]:
m4

array([[ 10.,   2.,   3.,  -4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])

In [82]:
m3

array([[ 10.,   2.,   3.],
       [ -4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

Outra forma de criar novos *arrays* é pela junção de *arrays* existentes, usando a função `concatenate`. Essa função recebe uma tupla de *arrays* e junta todos eles em um único, na ordem especificada.

In [83]:
a

array([1, 2, 3, 4, 5])

In [84]:
b = np.array([6,7,8,9,10])

In [85]:
np.concatenate((a, b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Um parâmetro opcional denominado `axis` pode ser usado no caso de *arrays* de mais de uma dimensão para especificar qual dimensão será usada na junção.

Primeiro vamos transformar `a` e `b` em *arrays* com duas dimensões, de *shape* (1,5).

In [86]:
a = a.reshape((1,5))

In [87]:
b = b.reshape((1,5))

In [88]:
a.shape

(1, 5)

In [89]:
a

array([[1, 2, 3, 4, 5]])

In [90]:
np.concatenate((a,b), axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [91]:
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

Uma forma opcional de adicionar uma nova dimensão é através do uso de `newaxis`.

In [92]:
x = np.arange(0,10,0.5)

In [93]:
x.shape

(20,)

In [94]:
y = x[:, np.newaxis]

In [95]:
y.shape

(20, 1)

In [96]:
y

array([[ 0. ],
       [ 0.5],
       [ 1. ],
       [ 1.5],
       [ 2. ],
       [ 2.5],
       [ 3. ],
       [ 3.5],
       [ 4. ],
       [ 4.5],
       [ 5. ],
       [ 5.5],
       [ 6. ],
       [ 6.5],
       [ 7. ],
       [ 7.5],
       [ 8. ],
       [ 8.5],
       [ 9. ],
       [ 9.5]])

In [97]:
z = x[np.newaxis, :]

In [98]:
z.shape

(1, 20)

In [99]:
z

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
         5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5]])

Vejamos agora como gerar algums *arrays* especiais. O primeiro é um *array* com todos os valores em zero.

In [100]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Se queremos *arrays* com mais dimensões, basta fornecer uma tupla com o *shape* adequado.

In [101]:
np.zeros((5,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

Podemos também especificar o tipo dos elementos.

In [102]:
np.zeros((5,4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Outro *array* especial tem todos os seus valores inicializados em um.

In [103]:
np.ones((3,7))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

Suponha agora que temos um *array* e queremos criar um outro com o mesmo formato mas todos os valores em zero (também funciona com um).

Uma forma de fazer isso é passar o *shape* do *array* original para a função `zeros`:

In [104]:
m3

array([[ 10.,   2.,   3.],
       [ -4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [105]:
np.zeros(m3.shape)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Mas podemos simplesmente usar a função `zeros_like` (ou `ones_like`).

In [106]:
z = np.zeros_like(m3)

In [107]:
o = np.ones_like(m3)

In [108]:
z, o

(array([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]))

Para *arrays* são definidos todos os operadores artiméticos. Eles operam realizando as operações elemento a elemento entre elementos correspondentes dos *arrays*

In [109]:
m3

array([[ 10.,   2.,   3.],
       [ -4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [110]:
o

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [111]:
m3 + o

array([[ 11.,   3.,   4.],
       [ -3.,   6.,   7.],
       [  8.,   9.,  10.],
       [ 11.,  12.,  13.]])

In [112]:
m3 - o

array([[  9.,   1.,   2.],
       [ -5.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.]])

In [113]:
m3 * m3

array([[ 100.,    4.,    9.],
       [  16.,   25.,   36.],
       [  49.,   64.,   81.],
       [ 100.,  121.,  144.]])

In [114]:
m3 / o

array([[ 10.,   2.,   3.],
       [ -4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

É interessante notar como o NumPy lida com divisões por zeros:

In [115]:
o / z

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([[ inf,  inf,  inf],
       [ inf,  inf,  inf],
       [ inf,  inf,  inf],
       [ inf,  inf,  inf]])

Também são definidas operações entre *arrays* e escalares: A operação é realizada entre cada elemento do *array* e o escalar.

In [116]:
m3 ** 2

array([[ 100.,    4.,    9.],
       [  16.,   25.,   36.],
       [  49.,   64.,   81.],
       [ 100.,  121.,  144.]])

In [117]:
m3 ** 0

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [118]:
m3 + 1

array([[ 11.,   3.,   4.],
       [ -3.,   6.,   7.],
       [  8.,   9.,  10.],
       [ 11.,  12.,  13.]])

In [119]:
o * 2

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [120]:
4 * m3 - (2 * m3 - 2) ** 3

array([[ -5792.,      0.,    -52.],
       [   984.,   -492.,   -976.],
       [ -1700.,  -2712.,  -4060.],
       [ -5792.,  -7956., -10600.]])

Todas essa operações geram um **novo** *array*. Se quisermos deixar os resultados no *array*, usamos os operadores de atribuição do tipo `+=`.

In [121]:
z += 5

In [122]:
z

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

Lembre-se que o produto entre *arrays*, como as outras operações, realiza o produto elemento a elemento.

In [123]:
m1 = (2 * np.ones((3,3))); m2 = (3 * np.ones((3,3)))

In [124]:
m1 * m2

array([[ 6.,  6.,  6.],
       [ 6.,  6.,  6.],
       [ 6.,  6.,  6.]])

Se quisermos o produto de matrizes, devemos usar a função `dot`.

In [125]:
np.dot(m1, m2)

array([[ 18.,  18.,  18.],
       [ 18.,  18.,  18.],
       [ 18.,  18.,  18.]])

Outra forma de gerar *arrays* bastante útil é através de números aleatórios.

O NumPy possui um módulo de número aleatórios próprio, `numpy.random`, que possui funções que geram *arrays* cujos elementos são gerados por diveras distribuições aleatórias.

Basta escolher a distribuição desejada, fornecer os seus parâmetros e especificar o *shape* do *array* desejado. Veja a grande variedade de opções no [site de documentação](http://docs.scipy.org/doc/numpy/reference/routines.random.html).

Por exemplo, se queremos uma matriz com número aleatórios uniformes entre 0 e 1, podemos usar `numpy.random.random`.

In [126]:
m4 = np.random.random((3,4))

In [127]:
m4

array([[  9.91669709e-01,   6.00015777e-01,   1.37765026e-01,
          6.83990442e-01],
       [  7.40777415e-04,   1.85303027e-01,   8.08054285e-01,
          1.72707609e-01],
       [  6.74484621e-01,   6.06361257e-01,   4.20971674e-01,
          5.50439128e-01]])

A classe `numpy.array` fornece uma grande quantidade de métodos que permitem realizar operações sobre os elementos do `array`. Seguem alguns exemplos.

Para calcular a soma total de todos os valores do *array* usamos `sum`.

In [128]:
m4.sum()

5.8325033327544089

Podemos também encontrar o menor valor (`min`) ou o maior valor (`max`).

In [129]:
m4.min()

0.00074077741528644214

In [130]:
m4.max()

0.99166970893944295

Se quisermos saber a posição (índice) do mínimo ou máximo, usamos `argmin` ou `argmax`, respectivamente. O índice retornado será o índice do valor correspondente na versão `flatten` do *array* (isto é, ele é considerado de apenas uma dimensão durante a busca).

In [131]:
m4.argmin()

4

In [132]:
m4.argmax()

0

Podemos também calcular média (`mean`) e desvio padrão (`std`) dos valores.

In [133]:
m4.mean()

0.48604194439620074

In [134]:
m4.std()

0.29087939636310173

Várias dessas funções têm a opção de especificar um eixo sobre o qual a operação deve ser realizada. Nesse caso, ao invés de realizar a operação sobre todos os valores do *array* e retornar um único valor, a operação é executada sobre todos os valores em cada uma das possibilidades do eixo especificado, e se retorna um *array* de resultados.

In [135]:
m4.shape

(3, 4)

In [136]:
m4.sum(axis=0)

array([ 1.66689511,  1.39168006,  1.36679099,  1.40713718])

Como `m4` tem 3 linhas por 4 colunas, ao especificarmos para `sum` o parâmetro `axis=0` (linhas) estamos pedindo que a soma seja feita percorrendo as linhas, resultando em uma soma por coluna.

Se pedirmos `axis=1` as somas serão por coluna, resultado em uma soma por linha.

In [137]:
m4.sum(axis=1)

array([ 2.41344095,  1.1668057 ,  2.25225668])

O mesmo vale para outros métodos.

In [138]:
m4.mean(axis=0)

array([ 0.5556317 ,  0.46389335,  0.455597  ,  0.46904573])

Outra característica do NumPy é que ele redefine todas as funções matemáticas do módulo `math`, de forma que elas podem operar sobre *arrays*. Elas vão operar sobre todos os elementos do *array*.

In [139]:
np.sqrt(m4)

array([[ 0.99582614,  0.77460685,  0.37116711,  0.82703715],
       [ 0.02721723,  0.43046838,  0.8989184 ,  0.41558105],
       [ 0.82127013,  0.77869202,  0.6488233 ,  0.74191585]])

In [140]:
np.exp(m4)

array([[ 2.6957318 ,  1.82214755,  1.14770584,  1.98177011],
       [ 1.00074105,  1.2035831 ,  2.24353845,  1.18851854],
       [ 1.96302102,  1.83374671,  1.52344112,  1.7340143 ]])

In [141]:
np.sin(m4)

array([[  8.36940965e-01,   5.64655494e-01,   1.37329661e-01,
          6.31890868e-01],
       [  7.40777348e-04,   1.84244382e-01,   7.22944237e-01,
          1.71850304e-01],
       [  6.24494874e-01,   5.69881185e-01,   4.08647485e-01,
          5.23061546e-01]])

Uma forma versátil de gerar novos *arrays* é fornecendo uma função que, dados os índices do elemento no *array*, retorne o valor correspondente.

Isso é realizado pela função `fromfunction`, cujo primeiro parâmetro é a função que recebe os índices e retorna o valor e o segundo parâmetro é o *shape* da função. Adicionalmente, podemos especificar o tipo.

In [142]:
np.fromfunction(lambda i: i**2 - 1, (6,)) 

array([ -1.,   0.,   3.,   8.,  15.,  24.])

In [143]:
np.fromfunction(lambda i, j: i - j, (4,4))

array([[ 0., -1., -2., -3.],
       [ 1.,  0., -1., -2.],
       [ 2.,  1.,  0., -1.],
       [ 3.,  2.,  1.,  0.]])

### Formas adicionais de indexação

Além de fornecer inteiros ou *slices* para os índices, podemos também fornecer outros *arrays*, como abaixo.

In [144]:
meuarray = np.arange(0,15,1.5)

In [145]:
meuarray.shape

(10,)

In [146]:
meuarray

array([  0. ,   1.5,   3. ,   4.5,   6. ,   7.5,   9. ,  10.5,  12. ,  13.5])

Uma forma é criar um *array* de inteiros com os índices que quermos acessar.

In [147]:
indices = np.array([2,4,7])

Em seguida, usamos esse *array* como "índice". Ele irá selecionar os elementos que correpondem aos índices fornecidos.

In [148]:
meuarray[indices]

array([  3. ,   6. ,  10.5])

A indexação apenas retorna um *view* sobre o *array*. Podemos então alterar os correspondentes elementos do *array* original mexendo nesses valores.

In [149]:
meuarray[indices] = -1

In [150]:
meuarray

array([  0. ,   1.5,  -1. ,   4.5,  -1. ,   7.5,   9. ,  -1. ,  12. ,  13.5])

Outra forma de indexação seletiva é criarmos um *array* de booleanos (`True` ou `False`), do mesmo tamanho do *array* a ser indexados. Os elementos que contém `True` serão selecionados, enquanto que os com `False` serão ignorados.

In [151]:
negativos = meuarray < 0

In [152]:
negativos.shape

(10,)

In [153]:
negativos.dtype

dtype('bool')

In [154]:
negativos

array([False, False,  True, False,  True, False, False,  True, False, False], dtype=bool)

In [155]:
meuarray[negativos]

array([-1., -1., -1.])

In [156]:
meuarray[negativos] *= 2

In [157]:
meuarray

array([  0. ,   1.5,  -2. ,   4.5,  -2. ,   7.5,   9. ,  -2. ,  12. ,  13.5])

### Operações de álgebra linear

Algumas operações de álgebra linear considerando os *arrays* como matrizes são definidas.

In [158]:
mq = np.random.random((4,4))

In [159]:
mq

array([[ 0.76218581,  0.24369466,  0.78616137,  0.54711778],
       [ 0.29326377,  0.33273465,  0.34948161,  0.2563354 ],
       [ 0.32416863,  0.88708715,  0.19900623,  0.48399663],
       [ 0.10361215,  0.98058243,  0.69042698,  0.08605326]])

A matriz transposta pode ser acessada pelo método `transpose`.

In [160]:
mq.transpose()

array([[ 0.76218581,  0.29326377,  0.32416863,  0.10361215],
       [ 0.24369466,  0.33273465,  0.88708715,  0.98058243],
       [ 0.78616137,  0.34948161,  0.19900623,  0.69042698],
       [ 0.54711778,  0.2563354 ,  0.48399663,  0.08605326]])

O *traço* da matriz (soma dos elementos na diagonal principal) é calculado pela função `trace`.

In [161]:
np.trace(mq)

1.3799799551519447

Podemos criar uma matriz identidade com a função `eye` (pois rima com `I`, de identidade, em inglês).

In [162]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

Operações mais complexas estão disponíveis no módulo `numpy.linalg`.

Por exemplo, a inversa de uma matriz:

In [163]:
np.linalg.inv(mq)

array([[  85.33465855, -281.5741899 ,   47.00833613,   31.81109238],
       [  20.08735592,  -68.53493449,   12.10985935,    8.32797455],
       [ -31.22297942,  105.85594808,  -18.78312051,  -11.16765241],
       [ -81.13380388,  270.67954444,  -43.89115428,  -31.97824993]])

Ou o conjunto de autovalores e correspondente autovetores.

In [164]:
autoval, autovet = np.linalg.eig(mq)

In [165]:
autoval

array([ 1.75741431,  0.09110423, -0.02311495, -0.44542364])

In [166]:
autovet

array([[ -6.91726451e-01,  -7.49247423e-01,  -6.69124072e-01,
          4.18391719e-02],
       [ -3.35668512e-01,  -8.84654781e-02,  -1.86508074e-01,
         -2.35538217e-04],
       [ -4.69699698e-01,   2.42544693e-01,   2.59200515e-01,
         -6.13175771e-01],
       [ -4.33847163e-01,   6.09896902e-01,   6.71046055e-01,
          7.88837690e-01]])